name: Deploy Images to GHCR

on:
  release:
    types: [ created ]

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Store'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CR_PAT}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/MrMohebi/froward-proxy:${{ github.ref_name }}
          docker push ghcr.io/MrMohebi/froward-proxy:${{ github.ref_name }}
          docker tag ghcr.io/MrMohebi/froward-proxy:${{ github.ref_name }} ghcr.io/MrMohebi/froward-proxy:latest
          docker push ghcr.io/MrMohebi/froward-proxy:latest